activation_appnp: sigmoid
activation_gat: elu
alpha: 0.3
appnp_K: 3
backbone: resnet50
class_weights:
- 0.34670324884591935
- 64.20161290322581
- 1.3816383200277682
- 2.6572096128170895
dropout: 0.2
f_max: null
f_min: 0.0
focal_gamma: 2.0
freeze_backbone: false
gat_heads: 1
gat_out_features: 512
gcn_out_features: 512
grid_size: !!python/tuple
- 3
- 3
hop_length: 160
img_size: 224
inter_adj_mode: grid8
intra_adj_mode: full
label_smoothing: 0.001
learning_rate: 0.001
max_epochs: 100
n_fft: 16000
n_mels: 8092
num_classes: 4
pool_size: !!python/tuple
- 3
- 3
pretrained: true
sample_rate: 32000
warmup_epochs: 5
waveform_input: true
weight_decay: 0.00025
