cqt_bpo: 12
cqt_ch: 128
cqt_hop: 64
cqt_n_bins: 84
demon_ch: 64
demon_hop: 64
demon_n_fft: 2048
dropout: 0.15
fusion_T: 64
fusion_dim: 192
gabor_ch: 128
gabor_kernel: 257
gabor_n_filters: 64
gain_prob: 0.8
gain_range: 0.4
lambda_param: 0.005
learning_rate: 0.0003
max_epochs: 1
n_heads: 2
noise_prob: 0.8
noise_snr_max: 30.0
noise_snr_min: 10.0
num_classes: 4
projection_dim: 2048
projection_hidden: 2048
sample_rate: 5120
shift_max: 0.1
shift_prob: 0.5
warmup_epochs: 1
weight_decay: 0.01
