activation_appnp: sigmoid
activation_gat: elu
alpha: 0.3
appnp_K: 3
backbone: resnet50
class_weights:
- 0.3510800452922219
- 15.326045627376425
- 1.3990801804928845
- 2.690754339118825
dropout: 0.2
f_max: null
f_min: 0.0
focal_gamma: 2.0
freeze_backbone: false
gat_heads: 1
gat_out_features: 512
gcn_out_features: 512
grid_size: !!python/tuple
- 3
- 3
hop_length: 512
img_size: 224
inter_adj_mode: grid8
intra_adj_mode: full
label_smoothing: 0.001
learning_rate: 0.001
max_epochs: 50
n_fft: 4096
n_mels: 512
num_classes: 4
pool_size: !!python/tuple
- 3
- 3
pretrained: true
sample_rate: 32000
warmup_epochs: 5
waveform_input: true
weight_decay: 0.00025
