ceps_high_q: 15
ceps_low_q: 3
cssd_alpha: 1.0
cssd_degrade_prob: 0.5
cssd_degrade_sr: 2048
cssd_temp: 4.0
d_model: 160
dart_dropout: 0.1
dart_heads: 4
dilation_rates:
- 2
- 4
- 8
drop_path_rate: 0.13943931663969023
dropout: 0.17315627607271478
ema_momentum: 0.999
focal_gamma: 2.0
g_ch: 48
gabor_kernel: 129
gabor_n_filters: 64
gain_prob: 0.7
l_ch: 16
label_smoothing: 0.05
learning_rate: 0.00010264874518489225
lofar_freq_bins: 256
lofar_hop: 51
lofar_n_fft: 1024
lofar_time_bins: 32
mamba_d_conv: 4
mamba_d_state: 16
mamba_expand: 2
max_epochs: 100
mixup_alpha: 0.3
n_dart: 1
n_mamba: 2
n_s4: 2
nb_n_fft: 4096
noise_prob: 0.5
noise_snr_max: 30.0
noise_snr_min: 0.0
num_classes: 4
onset_patch: 4
s4_d_state: 64
s_ch: 64
sample_rate: 5120
scale: 8
spec_hop: 51
spec_n_mels: 32
stem_stride: 4
use_stream_l: false
use_stream_s: true
warmup_epochs: 10
wb_n_fft: 1024
weight_decay: 0.001
