ceps_high_q: 12
ceps_low_q: 3
cssd_alpha: 1.0
cssd_degrade_prob: 0.5
cssd_degrade_sr: 2048
cssd_temp: 4.0
d_model: 128
dart_dropout: 0.1
dart_heads: 4
dilation_rates:
- 1
- 2
- 4
- 8
drop_path_rate: 0.5570308292627142
dropout: 0.08899863008405066
ema_momentum: 0.999
focal_gamma: 2.0
g_ch: 48
gabor_kernel: 129
gabor_n_filters: 64
gain_prob: 0.7
l_ch: 32
label_smoothing: 0.05
learning_rate: 0.00011430983876313228
lofar_freq_bins: 256
lofar_hop: 51
lofar_n_fft: 4096
lofar_time_bins: 32
mamba_d_conv: 4
mamba_d_state: 16
mamba_expand: 2
max_epochs: 100
mixup_alpha: 0.3
n_dart: 2
n_mamba: 2
n_s4: 2
nb_n_fft: 4096
noise_prob: 0.5
noise_snr_max: 40.0
noise_snr_min: 20.0
num_classes: 4
onset_patch: 4
s4_d_state: 64
s_ch: 48
sample_rate: 5120
scale: 8
spec_hop: 51
spec_n_mels: 48
stem_stride: 8
use_stream_l: false
use_stream_s: false
warmup_epochs: 10
wb_n_fft: 1024
weight_decay: 0.001
