con_conv_kernel: 31
con_drop_path: 0.1
con_dropout: 0.1
con_model_dim: 128
con_n_blocks: 4
con_n_heads: 16
focal_gamma: 2.0
gain_prob: 0.7
hop_length: 320
learning_rate: 0.0003
max_epochs: 60
mixup_alpha: 0.0
n_mels: 128
net_channels: 128
net_dilations:
- 2
- 4
- 8
net_drop_path: 0.1
net_dropout: 0.24
net_scale: 8
noise_prob: 0.5
pos_weight: 4.526553280111073
sample_rate: 32000
target_class_idx: 1
target_class_name: Tanker
warmup_epochs: 8
weight_decay: 0.012
