channels: 64
class_weights: null
dilation_rates:
- 2
- 4
- 8
drop_path_rate: 0.0868
dropout: 0.384
focal_gamma: 2.048
gain_prob: 0.7409
gain_range: !!python/tuple
- 0.6
- 1.4
hop_length: 320
kernel_size: 3
label_smoothing: 0.00963
learning_rate: 0.0001679
lifter_high_q: 25
lifter_low_q: 3
max_epochs: 100
mixup_alpha: 0.1726
n_mels: 128
nb_n_fft: 4096
noise_prob: 0.6546
noise_snr_db: !!python/tuple
- 20.0
- 40.0
num_classes: 3
sample_rate: 32000
scale: 8
warmup_epochs: 10
wb_n_fft: 1024
weight_decay: 0.01252
